const W=960,H=540,T=32,MAG=12,cv=document.getElementById('game'),ctx=cv.getContext('2d'),hud=document.getElementById('hud'),screen=document.getElementById('screen'),banner=document.getElementById('banner');
const rooms=[['MAIN HALL',10,6,10,8,'#2a2735'],['WEST CORRIDOR',2,8,8,4,'#1d2230'],['DINING ROOM',20,7,8,6,'#30231e'],['LIBRARY',3,2,7,6,'#202b26'],['EAST CORRIDOR',20,13,9,4,'#20202b'],['GUEST ROOM',22,2,6,5,'#2d242d'],['MASTER SUITE',3,13,8,5,'#2e2524']].map(([name,x,y,w,h,color])=>({name,x,y,w,h,color}));
const doors=[[10,10],[6,8],[20,10],[24,7],[18,13],[7,13]], furn=[['stairs',14,7,2,1],['table',22,9,4,1],['shelf',5,4,3,1],['bed',24,3,2,2],['bed',5,15,3,2],['clock',16,12,1,1],['typewriter',12,12,2,1]].map(([t,x,y,w,h])=>({t,x,y,w,h}));
const seedItems=[['fuse',25,4],['fuse',5,4],['fuse',6,15],['ammo',23,10],['herb',15,13],['ammo',7,9],['herb',26,15]].map(([type,x,y])=>({type,x:x*T,y:y*T}));
let keys={},mouse={x:W/2,y:H/2},audio,state,mode='title';
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y); const roomAt=(x,y)=>rooms.find(r=>x>=r.x*T&&x<=(r.x+r.w)*T&&y>=r.y*T&&y<=(r.y+r.h)*T);
function buildState(){return {p:{x:15*T,y:10*T,hp:100,ammo:12,reserve:24,fuses:0,face:0,kills:0,shots:0,start:performance.now()},items:seedItems.map(i=>({...i})),blood:[],shake:0,flash:0,room:'MAIN HALL',enemies:[[4,9,2,'zombie'],[8,4,2,'zombie'],[24,10,2,'zombie'],[25,4,2,'zombie'],[7,15,2,'zombie'],[26,15,4,'brute'],[18,15,4,'brute']].map(([x,y,hp,kind])=>({x:x*T,y:y*T,hp,kind}))}}
function reset(){state=buildState();mode='play';screen.style.display='none';}
function beep(f=220,dur=.08,type='square',gain=.05){if(!audio){audio=new AudioContext();drone(audio)}let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.value=gain;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.stop(audio.currentTime+dur)}
function drone(c){let o=c.createOscillator(),g=c.createGain(),l=c.createOscillator(),lg=c.createGain();o.type='sawtooth';o.frequency.value=43;g.gain.value=.018;l.frequency.value=.09;lg.gain.value=.012;l.connect(lg).connect(g.gain);o.connect(g).connect(c.destination);o.start();l.start()}
function shoot(){let p=state?.p;if(mode!=='play'||!p)return;if(p.ammo<=0)return beep(80,.05);p.ammo--;p.shots++;state.flash=6;beep(95,.05,'square',.09);let target=state.enemies.filter(e=>e.hp>0&&d(p,e)<260).sort((a,b)=>d(p,a)-d(p,b))[0];if(target){target.hp--;state.shake=7;state.blood.push({x:target.x,y:target.y,r:8+Math.random()*10});if(target.hp<=0){p.kills++;beep(50,.16,'sawtooth',.08)}}}
function reload(){let p=state?.p,need=p?MAG-p.ammo:0,take=Math.min(need,p?.reserve||0);if(take>0){p.ammo+=take;p.reserve-=take;beep(310,.08,'triangle')}}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Enter'&&mode!=='play')reset();if(e.key.toLowerCase()==='r')reload();if(e.key.toLowerCase()==='p'&&mode==='play')mode='pause';else if(e.key.toLowerCase()==='p'&&mode==='pause')mode='play'});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
cv.addEventListener('mousemove',e=>{let r=cv.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height});cv.addEventListener('mousedown',shoot);
function update(dt){if(!state||mode!=='play')return;let p=state.p,g=navigator.getGamepads?.()[0],ax=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),ay=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(g){ax+=Math.abs(g.axes[0])>.2?g.axes[0]:0;ay+=Math.abs(g.axes[1])>.2?g.axes[1]:0;if(g.buttons[7].pressed)shoot();if(g.buttons[2].pressed)reload()}let len=Math.hypot(ax,ay)||1,sp=(keys.shift||g?.buttons[0].pressed?150:92),ox=p.x,oy=p.y;p.x+=ax/len*sp*dt;p.y+=ay/len*sp*dt;let r=roomAt(p.x,p.y);if(!r){p.x=ox;p.y=oy}else if(r.name!==state.room){state.room=r.name;banner.textContent=r.name;banner.classList.remove('show');void banner.offsetWidth;banner.classList.add('show')}p.face=Math.atan2(mouse.y-H/2,mouse.x-W/2);state.items=state.items.filter(it=>{if(Math.hypot(p.x-it.x,p.y-it.y)<28){if(it.type==='fuse')p.fuses++;if(it.type==='ammo')p.reserve+=12;if(it.type==='herb')p.hp=clamp(p.hp+35,0,100);beep(it.type==='fuse'?600:420,.12,'triangle');return false}return true});if(p.fuses>=3&&p.x>27*T&&p.y>13*T){let sec=(performance.now()-p.start)/1000;state.rank=sec<150&&p.hp>60?'S':sec<240?'A':p.hp>30?'B':'C';mode='win'}state.enemies.forEach(e=>{if(e.hp<=0)return;let de=d(p,e),speed=e.kind==='brute'?38:55;if(de<300){e.x+=(p.x-e.x)/de*speed*dt;e.y+=(p.y-e.y)/de*speed*dt}if(de<24){p.hp-=dt*(e.kind==='brute'?24:16);state.shake=3;if(p.hp<=0){p.hp=0;mode='dead'}}});state.shake*=.85;state.flash*=.7}
function draw(){if(!state)state=buildState();ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,W,H);let p=state.p,ox=W/2-p.x+(Math.random()-.5)*state.shake,oy=H/2-p.y+(Math.random()-.5)*state.shake;ctx.save();ctx.translate(ox,oy);ctx.fillStyle='#08090d';ctx.fillRect(-999,-999,3000,3000);rooms.forEach(r=>{ctx.fillStyle=r.color;ctx.fillRect(r.x*T,r.y*T,r.w*T,r.h*T);ctx.strokeStyle='#555064';ctx.lineWidth=5;ctx.strokeRect(r.x*T,r.y*T,r.w*T,r.h*T);for(let x=r.x;x<r.x+r.w;x++)for(let y=r.y;y<r.y+r.h;y++){ctx.strokeStyle='#151720';ctx.strokeRect(x*T,y*T,T,T)}});doors.forEach(([x,y])=>{ctx.fillStyle='#5b3a28';ctx.fillRect(x*T-10,y*T-14,20,28)});state.blood.forEach(b=>{ctx.fillStyle='#5a0710';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()});let sprites=[...furn.map(f=>({y:(f.y+f.h)*T,fn:()=>drawF(f)})),...state.items.map(i=>({y:i.y,fn:()=>drawItem(i)})),...state.enemies.filter(e=>e.hp>0).map(e=>({y:e.y,fn:()=>drawEnemy(e)})),{y:p.y,fn:()=>drawPlayer(p)}];sprites.sort((a,b)=>a.y-b.y).forEach(o=>o.fn());ctx.restore();darkness();overlay();hud.innerHTML=`<b>${p.hp>70?'FINE':p.hp>35?'CAUTION':'DANGER'}</b><span>AMMO ${p.ammo}/12 +${p.reserve}</span><span>FUSES ${p.fuses}/3</span><span>${state.room}</span><span>WASD/Mouse · Shift run · R reload · P pause · Gamepad</span>`;drawScreen()}
function drawF(f){ctx.fillStyle=f.t==='typewriter'?'#183c42':f.t==='bed'?'#49364b':'#4a3325';ctx.fillRect(f.x*T,f.y*T,f.w*T,f.h*T);ctx.fillStyle='#100';ctx.fillRect(f.x*T,(f.y+f.h)*T-4,f.w*T,8)}function drawItem(i){ctx.fillStyle=i.type==='fuse'?'#ffd34d':i.type==='herb'?'#46cf64':'#b0b6c0';ctx.fillRect(i.x-7,i.y-7,14,14)}function drawEnemy(e){ctx.fillStyle=e.kind==='brute'?'#6b3840':'#3c7a45';ctx.fillRect(e.x-11,e.y-22,22,30);ctx.fillStyle='#1b241b';ctx.fillRect(e.x-7,e.y-31,14,12)}function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.face);ctx.fillStyle='#4876a8';ctx.fillRect(-8,-14,16,24);ctx.fillStyle='#c7b08b';ctx.fillRect(2,-4,22,5);ctx.fillStyle='#222';ctx.fillRect(20,-6,13,4);ctx.restore()}function darkness(){let g=ctx.createRadialGradient(W/2,H/2,50,W/2,H/2,300);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.82)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(state.flash){ctx.fillStyle=`rgba(255,245,180,${state.flash/18})`;ctx.fillRect(0,0,W,H)}}function overlay(){ctx.fillStyle='rgba(255,255,255,.035)';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1)}
function drawScreen(){if(mode==='play'){screen.style.display='none';return}screen.style.display='grid';let text={title:'MANSION OF THE DEAD',pause:'PAUSED',dead:'YOU DIED',win:`ESCAPED — RANK ${state.rank||'S'}`}[mode];screen.innerHTML=`<h1>${text}</h1><p>Recover 3 fuses, unlock the east exit, and survive the hungry dead. Twin-stick mouse/gamepad controls, auto-aim pistol fire, haunted drone, and scarce supplies.</p><button>START / RESTART</button>`;screen.querySelector('button').onclick=reset}
let last=performance.now();function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}banner.textContent='MAIN HALL';banner.classList.add('show');requestAnimationFrame(loop);
